import { mkdirSync, readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { buildSystemPrompt, loadSkills } from "./lib.js";
import type { InstallerOptions } from "./lib.js";

export type InstallerHarness = "pi" | "codex" | "claude" | "opencode";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = join(__dirname, "..");

export function buildInstallerInitialMessage(step?: string): string {
  const configSteps = ["configure-policy", "policy"];
  const isConfigStep = step && configSteps.includes(step.toLowerCase());

  if (isConfigStep) {
    return `Inspect and configure OPA security policies for this smith-core environment (step '${step}'). Show current policy state and tool-access rules.`;
  }

  if (step) {
    return `Bootstrap this smith-core environment and execute step '${step}'.`;
  }

  return "Bootstrap this smith-core development environment. Ensure Docker services are up, Rust workspaces build, Node workspaces are installed, and report any fixes required.";
}

export function buildInstallerHarnessContext(opts: InstallerOptions): string {
  const agentsMd = readFileSync(join(PKG_ROOT, "agents.md"), "utf8").trim();
  const skills = loadSkills(join(PKG_ROOT, "skills"))
    .sort((a, b) => a.name.localeCompare(b.name));

  let content = "# Smith Installer Harness Context\n\n";
  content += "This file is generated by the Smith installer so different agent harnesses use the same instructions, skills, and repository-specific workflow.\n\n";
  content += "## Authoritative System Prompt\n\n";
  content += `${buildSystemPrompt(opts).trim()}\n\n`;
  content += "## AGENTS.md\n\n";
  content += `${agentsMd}\n\n`;
  content += "## Skill Index\n\n";
  for (const skill of skills) {
    content += `- ${skill.name}: ${skill.description}\n`;
  }
  content += "\n## Skill Bodies\n\n";
  for (const skill of skills) {
    content += `### ${skill.name}\n\n`;
    content += `${skill.content.trim()}\n\n`;
  }

  return content.trimEnd() + "\n";
}

export function writeInstallerHarnessContext(opts: InstallerOptions): string {
  const targetDir = join(opts.smithRoot, "var", "installer");
  mkdirSync(targetDir, { recursive: true });
  const targetPath = join(targetDir, "harness-context.md");
  writeFileSync(targetPath, buildInstallerHarnessContext(opts), "utf8");
  return targetPath;
}

export function normalizeInstallerHarness(raw?: string): InstallerHarness | null {
  if (!raw) return null;
  switch (raw.trim().toLowerCase()) {
    case "pi":
      return "pi";
    case "codex":
      return "codex";
    case "claude":
    case "claude-code":
      return "claude";
    case "opencode":
      return "opencode";
    default:
      return null;
  }
}
