server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/?(.*)'
        target_label: container_name
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: compose_service
    pipeline_stages:
      - docker: {}
      - match:
          selector: '{compose_service=~"envoy-gateway|envoy-egress"}'
          stages:
            - json:
                expressions:
                  method: method
                  path: path
                  status: response_code
                  duration_ms: duration
                  sandbox_id: sandbox_id
            - labels:
                method:
                path:
                status:
                duration_ms:
                sandbox_id:
